drop table MEMBER if EXISTS;
create table MEMBER(
  MEMBER_ID VARCHAR (255) NOT NULL,
  TEAM_ID VARCHAR (255),
  USERNAME VARCHAR (255),
  PRIMARY KEY (MEMBER_ID)
);

drop table TEAM if EXISTS;
CREATE TABLE TEAM(
  TEAM_ID VARCHAR (255) NOT NULL,
  NAME VARCHAR (255),
  PRIMARY KEY (TEAM_ID)
);

ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_TEAM
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM;

INSERT INTO TEAM(TEAM_ID, NAME) VALUES ('team1', '팀1');
INSERT INTO MEMBER(member_id, team_id, USERNAME) VALUES('member1', 'team1', '회원1');
INSERT INTO MEMBER(member_id, team_id, USERNAME) VALUES('member2', 'team1', '회원2');

SELECT T.* from MEMBER M JOIN TEAM T ON M.TEAM_ID = T.TEAM_ID WHERE M.MEMBER_ID='member1';